In [24]:
!pip install tensorflow

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

In [25]:
import tensorflow as tf

In [26]:
import pandas as pd
import numpy as np
df =pd.read_csv('Credit.csv')

In [27]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,unemployed,married,primary,1787,no,79.0,1,no
1,33.0,services,married,secondary,4789,yes,220.0,1,no
2,35.0,management,single,tertiary,1350,yes,185.0,1,no
3,30.0,management,married,tertiary,1476,yes,199.0,4,no
4,59.0,blue-collar,married,secondary,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,services,married,secondary,-333,yes,329.0,5,no
4517,57.0,self-employed,married,tertiary,-3313,yes,-153.0,1,no
4518,57.0,technician,married,secondary,295,no,151.0,11,no
4519,28.0,blue-collar,married,secondary,1137,no,129.0,4,no
4520,44.0,entrepreneur,single,tertiary,1136,yes,345.0,2,no

In [28]:
# df.to_csv('clean_Credit.csv')
from sklearn.datasets import load_iris
x , y= load_iris(return_X_y=True)

In [29]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [30]:
input_shape = x.shape[1]
input_shape

4

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [82]:
df = pd.read_csv('cleaned_dataset.csv')
x=df.drop('approval',axis=1)
y =df['approval']

In [97]:
x

       age  job  marital  education  balance  housing  duration  campaign
0     30.0   10        1          0     1787        0      79.0         1
1     33.0    7        1          1     4789        1     220.0         1
2     35.0    4        2          2     1350        1     185.0         1
3     30.0    4        1          2     1476        1     199.0         4
4     59.0    1        1          1        0        1     226.0         1
...    ...  ...      ...        ...      ...      ...       ...       ...
4496  99.0    7        1          1     -333        1     329.0         5
4497  57.0    6        1          2    -3313        1    -153.0         1
4498  57.0    9        1          1      295        0     151.0        11
4499  28.0    1        1          1     1137        0     129.0         4
4500  44.0    2        2          2     1136        1     345.0         2

[4501 rows x 8 columns]

In [100]:
input_shape = x.shape[1]

In [101]:
input_shape

8

In [102]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2)

In [113]:
model =Sequential()
model.add(Dense(units=128, activation='relu', input_shape=(input_shape,)))  ### input layer

# Dropout layer 
model.add(Dropout(0.2))

### hidden layer 
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))



# output layer 

model.add(Dense(units=1, activation='sigmoid')) 



model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [114]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_45 (Dense)                │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_50 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,161 (47.50 KB)

 Trainable params: 12,161 (47.50 KB)

 Non-trainable params: 0 (0.00 B)

In [115]:
model.fit(x_train , y_train , epochs=10)

Epoch 1/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6691 - loss: 15.7649
Epoch 2/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 1.2900
Epoch 3/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8255 - loss: 9.6099
Epoch 4/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8638 - loss: 0.7478
Epoch 5/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8664 - loss: 0.6414
Epoch 6/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8715 - loss: 0.5278
Epoch 7/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8450 - loss: 0.8306
Epoch 8/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8423 - loss: 0.9237
Epoch 9/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8564 - loss: 0.6183
Epoch 10/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8711 - loss: 17.2134

In [116]:
model.predict(  x_test)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

array([[3.94302160e-02],
       [2.55057734e-04],
       [8.95187657e-09],
       [6.17361255e-03],
       [1.49254416e-15],
       [8.68359621e-06],
       [1.58084338e-04],
       [2.99927123e-08],
       [4.94450978e-06],
       [3.45433271e-03],
       [1.25255194e-02],
       [4.74241679e-05],
       [3.64995612e-09],
       [1.38136660e-04],
       [1.72938854e-07],
       [2.30645314e-02],
       [4.86142184e-08],
       [2.38771667e-03],
       [3.87819637e-06],
       [1.70652238e-05],
       [9.51277849e-04],
       [1.03927832e-19],
       [2.17081630e-10],
       [7.05516914e-06],
       [1.32932757e-06],
       [1.70452610e-11],
       [1.03325862e-03],
       [1.36892396e-13],
       [1.02636921e-08],
       [1.67936422e-02],
       [6.70045763e-02],
       [1.67254257e-05],
       [2.00853869e-03],
       [4.12893096e-05],
       [6.79738167e-13],
       [1.58714524e-15],
       [6.54526055e-04],
       [3.47692367e-05],
       [2.25703523e-16],
       [3.30812218e-11],
       [9.34919401e-04],
       [2.65245808e-06],
       [4.54295769e-05],
       [3.99820432e-02],
       [1.93146616e-02],
       [6.97754603e-03],
       [1.02428615e-01],
       [3.53372193e-12],
       [4.79218361e-05],
       [1.17853766e-07],
       [3.53308292e-06],
       [1.58500086e-07],
       [9.37000368e-06],
       [6.79529649e-07],
       [4.28408089e-16],
       [8.26200903e-06],
       [9.01356165e-04],
       [1.45600343e-05],
       [7.80046956e-15],
       [6.08383678e-03],
       [5.19583082e-05],
       [4.84173466e-03],
       [1.36771472e-02],
       [1.08826569e-07],
       [6.90050307e-04],
       [5.72687611e-07],
       [7.87936827e-10],
       [1.05733008e-04],
       [7.80359755e-07],
       [9.13894596e-08],
       [1.40163517e-02],
       [1.30772812e-03],
       [1.31508184e-31],
       [7.98473620e-19],
       [3.71399096e-07],
       [9.79050219e-06],
       [9.27616748e-06],
       [7.41473696e-06],
       [2.33555897e-04],
       [6.84583485e-02],
       [3.38764954e-12],
       [1.07475976e-03],
       [4.20920696e-06],
       [9.57230513e-04],
       [1.03971106e-05],
       [5.28438902e-03],
       [7.08271784e-21],
       [0.00000000e+00],
       [1.81349651e-06],
       [1.77333732e-05],
       [2.38735127e-04],
       [2.23184307e-03],
       [5.18590568e-05],
       [4.91357269e-03],
       [1.46904588e-02],
       [1.88878812e-02],
       [2.36143563e-02],
       [4.10333014e-05],
       [1.77669432e-02],
       [9.77400783e-03],
       [2.63538080e-09],
       [6.83366598e-05],
       [4.92860681e-06],
       [3.54815484e-08],
       [1.09458400e-03],
       [5.26745198e-03],
       [2.45131459e-03],
       [9.07434271e-17],
       [2.05209100e-04],
       [2.52750714e-25],
       [2.72133707e-06],
       [1.14926428e-03],
       [5.62548696e-04],
       [3.43334936e-02],
       [6.19393133e-04],
       [5.93266333e-04],
       [3.98128733e-34],
       [1.62193828e-05],
       [2.00974531e-18],
       [7.61716135e-10],
       [7.17328396e-04],
       [1.65193303e-10],
       [2.41012452e-03],
       [6.56146789e-04],
       [0.00000000e+00],
       [1.66935213e-02],
       [1.65235397e-05],
       [6.12301333e-03],
       [1.01815196e-04],
       [8.74744287e-13],
       [3.73733992e-16],
       [2.50635017e-03],
       [3.42183374e-03],
       [7.46612159e-08],
       [6.90278560e-02],
       [2.07650446e-05],
       [2.86023337e-02],
       [0.00000000e+00],
       [1.84036970e-11],
       [1.07230514e-03],
       [4.81306824e-06],
       [6.42428582e-04],
       [4.27744118e-04],
       [2.39855098e-03],
       [5.62426082e-14],
       [1.74430888e-02],
       [5.56201092e-11],
       [3.38371880e-02],
       [2.52515334e-03],
       [1.74112190e-02],
       [9.03143373e-04],
       [1.95260402e-02],
       [1.35388154e-05],
       [6.26423433e-02],
       [4.97189118e-03],
       [3.38014914e-04],
       [8.61090255e-10],
       [1.77670340e-03],
       [3.33703213e-07],
       [4.13456075e-02],
       [4.54442208e-08],
       [3.80525012e-06],
       [3.48818824e-02],
       [6.96789697e-02],
       [7.18870852e-03],
       [3.75266857e-02],
       [1.23788211e-02],
       [4.73107889e-07],
       [6.93651324e-04],
       [8.27806643e-11],
       [1.81867203e-04],
       [4.27486561e-02],
       [1.43199459e-05],
       [2.01521181e-02],
       [6.83124736e-02],
       [3.40280026e-10],
       [1.23837452e-07],
       [3.70719557e-12],
       [3.35955434e-03],
       [6.09162124e-03],
       [1.77298225e-05],
       [2.26605474e-03],
       [3.88166644e-02],
       [2.36625201e-03],
       [1.03361999e-04],
       [3.19575512e-11],
       [3.75092707e-10],
       [1.19770067e-02],
       [4.09387167e-06],
       [4.64142151e-02],
       [2.97047105e-02],
       [6.57104887e-04],
       [2.32294205e-05],
       [2.41602268e-02],
       [1.64174773e-02],
       [5.94169982e-02],
       [5.99503641e-11],
       [1.42624009e-30],
       [7.28499761e-11],
       [3.91300006e-07],
       [3.94134931e-02],
       [3.07504932e-04],
       [5.25815599e-03],
       [3.47744481e-19],
       [1.07430592e-01],
       [1.04286673e-03],
       [1.61487344e-06],
       [5.51428006e-04],
       [1.45933148e-03],
       [1.07229399e-02],
       [9.54568502e-04],
       [9.08794347e-03],
       [9.48257744e-03],
       [1.41953556e-02],
       [1.98859831e-10],
       [2.46576313e-03],
       [5.03284973e-05],
       [1.36125018e-03],
       [5.81685966e-03],
       [4.13588801e-04],
       [4.78658840e-05],
       [9.49044897e-06],
       [2.40259944e-03],
       [7.98245747e-10],
       [1.57937047e-05],
       [3.72703411e-02],
       [5.51004428e-03],
       [5.39473240e-06],
       [3.35463046e-05],
       [5.28805688e-12],
       [5.76722584e-07],
       [5.07049775e-03],
       [2.22770104e-05],
       [1.58989001e-02],
       [9.49934311e-03],
       [1.78110022e-02],
       [2.25895084e-02],
       [1.47546814e-07],
       [1.13951159e-03],
       [2.24599518e-19],
       [4.32962086e-04],
       [8.85402560e-02],
       [6.31948387e-06],
       [4.71545383e-02],
       [7.68990605e-04],
       [1.16435367e-04],
       [0.00000000e+00],
       [3.43081318e-02],
       [4.28818576e-02],
       [1.23875660e-10],
       [4.05327981e-27],
       [4.34915712e-08],
       [4.39891693e-07],
       [3.74044888e-02],
       [4.60580830e-03],
       [5.54682426e-02],
       [2.14495777e-09],
       [1.54751930e-02],
       [2.25957716e-03],
       [2.85456744e-14],
       [1.06760730e-04],
       [8.81094329e-12],
       [7.87752142e-05],
       [1.61810985e-05],
       [2.60319677e-04],
       [3.44540849e-02],
       [4.03136546e-09],
       [2.19424292e-02],
       [1.50100868e-02],
       [4.11413293e-06],
       [1.88455489e-02],
       [3.02923005e-02],
       [2.98212274e-13],
       [1.82498042e-02],
       [9.08917864e-04],
       [2.35775062e-07],
       [8.29481916e-15],
       [7.32881622e-03],
       [3.66161457e-17],
       [7.13254651e-03],
       [1.56078371e-03],
       [6.23426727e-11],
       [2.83198990e-03],
       [1.69910479e-03],
       [2.77724117e-02],
       [1.02554949e-07],
       [4.23574261e-03],
       [9.96312220e-03],
       [5.36096469e-03],
       [5.82557789e-07],
       [6.84578852e-11],
       [6.67735934e-02],
       [1.07422341e-02],
       [5.08102914e-07],
       [4.94635206e-05],
       [4.57593333e-03],
       [9.61849187e-03],
       [3.27563728e-03],
       [0.00000000e+00],
       [4.93580228e-05],
       [1.40441614e-07],
       [5.32688532e-17],
       [5.49878413e-03],
       [1.98153575e-04],
       [1.68427755e-03],
       [1.37327497e-10],
       [2.15468369e-03],
       [7.13434312e-11],
       [2.58744080e-02],
       [1.82087254e-02],
       [2.11978294e-02],
       [2.29287576e-02],
       [1.94270893e-08],
       [1.12295570e-02],
       [6.10635263e-16],
       [1.73043670e-16],
       [2.71649775e-03],
       [3.41126508e-07],
       [2.58556884e-05],
       [1.02052214e-02],
       [5.32179820e-06],
       [5.46433114e-07],
       [4.84712757e-02],
       [8.06354495e-14],
       [2.83819986e-07],
       [4.95276600e-03],
       [8.95104938e-26],
       [1.56691782e-02],
       [2.04380862e-02],
       [4.86642914e-03],
       [7.52562832e-04],
       [4.99693351e-06],
       [6.85895234e-03],
       [9.68120527e-03],
       [2.89949821e-04],
       [4.49226761e-15],
       [6.82191638e-28],
       [3.43525223e-03],
       [1.30685294e-04],
       [2.30717371e-04],
       [3.32802216e-07],
       [4.06236947e-02],
       [3.31663876e-04],
       [9.09764320e-04],
       [1.56548467e-05],
       [4.28977236e-02],
       [2.85830665e-05],
       [8.05663317e-02],
       [4.48823236e-02],
       [1.74008973e-03],
       [1.59018629e-04],
       [2.39315815e-03],
       [3.62830946e-07],
       [5.78760186e-08],
       [2.12625600e-02],
       [3.30547366e-04],
       [2.05072041e-07],
       [5.10456855e-04],
       [1.54794438e-03],
       [5.82363964e-06],
       [2.74159770e-08],
       [7.36121494e-12],
       [9.89480511e-14],
       [1.70754711e-03],
       [8.95661302e-04],
       [9.17158462e-03],
       [8.45519384e-15],
       [1.82645600e-02],
       [4.10814350e-03],
       [1.27110453e-02],
       [3.09593772e-04],
       [2.71302531e-04],
       [5.15994942e-03],
       [6.76785464e-26],
       [1.61633616e-05],
       [6.14216280e-17],
       [2.74403618e-07],
       [9.41894017e-03],
       [1.50819328e-02],
       [1.71463307e-13],
       [1.09444563e-05],
       [2.67274817e-03],
       [1.27457520e-02],
       [3.06939576e-08],
       [7.27093209e-07],
       [2.95963604e-02],
       [5.51339518e-03],
       [5.89620512e-08],
       [1.17556099e-03],
       [1.37299268e-17],
       [8.85441992e-03],
       [1.79288789e-12],
       [2.80730887e-08],
       [1.20849120e-06],
       [2.84824669e-02],
       [9.52371303e-03],
       [2.63717282e-03],
       [7.73009288e-06],
       [2.03389217e-08],
       [4.62019544e-31],
       [4.55607427e-04],
       [1.32732059e-09],
       [1.66686817e-07],
       [5.60267363e-04],
       [3.05283209e-03],
       [9.53702965e-06],
       [1.76100111e-05],
       [1.45962701e-06],
       [2.68329959e-02],
       [8.33617616e-03],
       [9.82568972e-03],
       [2.74057942e-03],
       [6.98882673e-07],
       [2.05060709e-02],
       [1.75156351e-02],
       [4.17840172e-04],
       [3.45286207e-05],
       [1.68952291e-04],
       [1.92883405e-07],
       [4.02086414e-02],
       [7.27220173e-10],
       [6.80706593e-15],
       [9.19059530e-05],
       [1.68887071e-10],
       [2.06658412e-02],
       [6.86809013e-04],
       [2.77204290e-02],
       [5.89138363e-04],
       [4.43544462e-02],
       [6.69746223e-05],
       [1.56662648e-16],
       [0.00000000e+00],
       [2.01503350e-03],
       [9.58691544e-07],
       [1.10573603e-06],
       [1.02271400e-02],
       [5.67020152e-06],
       [3.17832178e-06],
       [1.54045823e-29],
       [1.72555924e-03],
       [5.36846276e-03],
       [2.27054721e-03],
       [6.26741153e-19],
       [3.47795780e-03],
       [7.31454975e-06],
       [6.97915239e-05],
       [6.62475871e-03],
       [1.31020070e-10],
       [3.88937740e-04],
       [2.14680069e-04],
       [2.08404241e-03],
       [7.32267462e-03],
       [3.29312810e-04],
       [6.48893774e-07],
       [7.95712462e-04],
       [4.57232233e-07],
       [3.28414738e-02],
       [1.32622098e-15],
       [3.14368168e-03],
       [3.15000737e-09],
       [2.76121500e-06],
       [0.00000000e+00],
       [3.13630177e-10],
       [1.07308608e-02],
       [3.95775052e-10],
       [1.15862327e-04],
       [1.31685374e-04],
       [4.56634031e-21],
       [5.14905341e-03],
       [9.13651910e-09],
       [2.62782050e-05],
       [3.14884301e-06],
       [6.05278723e-02],
       [2.27276155e-06],
       [1.29952008e-04],
       [4.98234574e-03],
       [1.24226508e-05],
       [8.27012833e-11],
       [8.74186057e-08],
       [8.51744517e-06],
       [3.97225432e-02],
       [7.87475728e-05],
       [2.84783312e-07],
       [9.38607201e-08],
       [3.63576791e-09],
       [1.28960954e-02],
       [2.42274647e-04],
       [1.48182977e-02],
       [7.45881489e-03],
       [7.63338059e-03],
       [1.88719321e-06],
       [2.46184965e-04],
       [8.03430472e-03],
       [2.32103793e-03],
       [2.82029877e-03],
       [2.09068816e-08],
       [4.60902766e-06],
       [2.48182403e-07],
       [1.51508997e-04],
       [2.64503225e-03],
       [7.36193537e-11],
       [1.61772095e-05],
       [1.39020514e-02],
       [0.00000000e+00],
       [1.97910708e-07],
       [8.64721369e-03],
       [4.26031656e-05],
       [2.06481703e-02],
       [8.55628990e-13],
       [1.01644364e-04],
       [3.81674687e-03],
       [2.99928843e-06],
       [6.45152933e-04],
       [2.53789494e-16],
       [2.81816431e-10],
       [7.46075995e-03],
       [8.82032095e-04],
       [2.63046124e-04],
       [3.86627041e-09],
       [6.11639917e-02],
       [2.39377469e-02],
       [9.07238507e-10],
       [3.78803009e-07],
       [4.89730872e-02],
       [1.12608122e-02],
       [2.38744178e-06],
       [1.84781533e-02],
       [2.19824855e-04],
       [1.30584260e-04],
       [9.95152502e-11],
       [4.93031749e-08],
       [1.16767827e-02],
       [2.96444576e-02],
       [1.83462525e-05],
       [1.43643003e-04],
       [7.97960791e-04],
       [3.31220421e-28],
       [5.95042184e-06],
       [8.29188793e-04],
       [2.37645265e-02],
       [6.17699046e-03],
       [1.06929685e-03],
       [4.88738809e-03],
       [0.00000000e+00],
       [2.88116002e-08],
       [5.69992665e-07],
       [5.78906096e-04],
       [2.27584081e-07],
       [1.50582718e-33],
       [4.48808223e-02],
       [6.78221657e-09],
       [2.37786658e-02],
       [3.89260314e-02],
       [9.74387349e-10],
       [2.38404624e-04],
       [2.97612656e-04],
       [3.60198366e-03],
       [6.45110616e-03],
       [1.20089262e-05],
       [4.66773535e-08],
       [4.21529221e-05],
       [4.12704248e-04],
       [9.22228559e-04],
       [7.61330199e-09],
       [1.79370623e-02],
       [1.35997413e-02],
       [1.95475264e-26],
       [2.29179520e-09],
       [6.74356357e-04],
       [1.07233587e-03],
       [1.21319325e-16],
       [3.74308430e-19],
       [1.42639719e-12],
       [5.73661039e-03],
       [3.75142554e-05],
       [2.58907271e-11],
       [1.42315207e-02],
       [0.00000000e+00],
       [8.26700580e-06],
       [1.06945708e-02],
       [9.00802320e-07],
       [5.20730449e-04],
       [6.39700571e-25],
       [2.40899768e-04],
       [1.11188051e-22],
       [2.73893463e-10],
       [1.00298137e-20],
       [7.19809577e-07],
       [1.96752691e-04],
       [5.32256128e-16],
       [4.08479013e-04],
       [2.91300025e-02],
       [6.19450157e-06],
       [1.07314627e-15],
       [1.35609433e-02],
       [2.29662794e-04],
       [4.20085122e-08],
       [3.62157263e-02],
       [9.74641182e-03],
       [1.88389618e-04],
       [2.64302358e-08],
       [1.19759338e-02],
       [4.08482598e-17],
       [1.11866603e-03],
       [1.07954349e-03],
       [8.51809338e-04],
       [2.56338157e-03],
       [6.03819685e-03],
       [1.24691790e-02],
       [2.79275351e-04],
       [2.99694724e-02],
       [1.34275906e-05],
       [2.21417751e-09],
       [1.26004510e-04],
       [2.25815984e-05],
       [3.19814135e-05],
       [7.36637230e-05],
       [3.72860618e-02],
       [3.74641029e-09],
       [1.55098961e-10],
       [2.00845443e-06],
       [7.98781331e-19],
       [3.67319374e-19],
       [2.67919731e-08],
       [1.40956166e-04],
       [2.72709038e-03],
       [0.00000000e+00],
       [4.39272868e-03],
       [7.66065597e-17],
       [8.68239347e-03],
       [3.47984731e-11],
       [7.22821909e-08],
       [1.72769697e-03],
       [1.65218225e-05],
       [6.21432364e-02],
       [1.54872096e-19],
       [9.97792722e-06],
       [6.63548244e-11],
       [2.26799073e-03],
       [5.76579835e-19],
       [5.01695513e-06],
       [2.26388476e-03],
       [2.04647798e-02],
       [3.10646780e-02],
       [8.24422948e-03],
       [1.35853137e-15],
       [5.24206314e-07],
       [2.47841719e-10],
       [1.98449328e-08],
       [3.13448254e-05],
       [3.05086151e-10],
       [1.42138479e-05],
       [2.32708230e-09],
       [1.89463962e-02],
       [1.20887964e-03],
       [4.89812101e-06],
       [6.26238994e-03],
       [7.65353363e-08],
       [1.15551185e-04],
       [7.26513006e-03],
       [2.78019905e-03],
       [1.15736458e-29],
       [5.16499696e-08],
       [6.35781697e-24],
       [3.16929584e-03],
       [7.43392150e-07],
       [3.86529299e-03],
       [1.88836537e-03],
       [1.27329084e-03],
       [8.11165664e-05],
       [7.11717334e-08],
       [1.61739705e-26],
       [6.99100259e-04],
       [2.48290622e-03],
       [4.67794692e-09],
       [1.45832160e-02],
       [2.17319575e-06],
       [1.45406621e-02],
       [1.00808474e-03],
       [1.68810319e-02],
       [5.81096392e-04],
       [1.78776915e-12],
       [3.10173818e-05],
       [2.96550803e-03],
       [1.90052111e-02],
       [1.08567933e-13],
       [4.81294323e-04],
       [1.42772672e-14],
       [3.66248889e-03],
       [1.16106737e-02],
       [5.07157703e-04],
       [4.02873930e-08],
       [1.06819396e-04],
       [3.34807485e-02],
       [1.85165554e-02],
       [3.50298896e-03],
       [8.95036850e-03],
       [1.56951100e-02],
       [2.01812992e-03],
       [6.89665758e-05],
       [1.60601218e-07],
       [4.50996042e-04],
       [7.03111431e-03],
       [9.68633336e-04],
       [1.67876433e-32],
       [1.06669162e-07],
       [3.73888819e-04],
       [7.27869454e-04],
       [1.03617004e-09],
       [0.00000000e+00],
       [3.47591049e-06],
       [5.28571289e-03],
       [1.03444471e-27],
       [4.15066211e-03],
       [2.26034126e-06],
       [1.63767848e-03],
       [6.55865967e-02],
       [7.02060146e-11],
       [1.52158020e-06],
       [8.64878800e-19],
       [4.64527495e-02],
       [1.49450069e-02],
       [2.51201884e-04],
       [9.44766123e-03],
       [1.37385019e-08],
       [0.00000000e+00],
       [1.10237778e-07],
       [1.15792407e-02],
       [1.75218345e-04],
       [1.47232407e-04],
       [2.73032952e-02],
       [1.93551205e-05],
       [1.68309962e-05],
       [1.39596763e-11],
       [3.01155142e-11],
       [0.00000000e+00],
       [5.77656152e-12],
       [1.18411286e-03],
       [6.91646487e-02],
       [1.55332396e-02],
       [3.29856155e-03],
       [1.08417154e-27],
       [9.17174034e-08],
       [4.74955499e-07],
       [1.38057658e-04],
       [3.52556090e-05],
       [2.03312305e-03],
       [7.26407416e-06],
       [1.00625921e-02],
       [3.41793010e-03],
       [1.03991004e-02],
       [2.58516565e-18],
       [3.80465668e-03],
       [6.60176956e-05],
       [2.80919168e-02],
       [5.60727390e-03],
       [1.03187447e-09],
       [1.02204981e-03],
       [1.97222596e-03],
       [2.32831519e-02],
       [3.24093139e-06],
       [8.69537704e-03],
       [1.69904430e-26],
       [2.59573849e-26],
       [7.13881482e-13],
       [6.04235697e-22],
       [1.41412957e-05],
       [8.05391828e-05],
       [4.83586127e-03],
       [0.00000000e+00],
       [3.08666509e-02],
       [4.88028780e-13],
       [2.69341581e-02],
       [5.20560097e-05],
       [1.33061269e-02],
       [1.17640710e-02],
       [1.03343382e-06],
       [5.59798100e-05],
       [2.11135802e-08],
       [1.11731363e-03],
       [5.28012810e-04],
       [1.89423881e-04],
       [2.36097218e-23],
       [6.98745763e-03],
       [1.48777878e-02],
       [9.78400093e-03],
       [2.28977930e-02],
       [1.56979058e-13],
       [6.02171873e-04],
       [3.24365776e-03],
       [1.06999755e-03],
       [6.37059938e-03],
       [5.65266873e-07],
       [4.81032316e-08],
       [1.45732749e-11],
       [7.65666118e-05],
       [2.24908547e-12],
       [2.61954207e-04],
       [1.65940151e-02],
       [3.13004966e-05],

In [117]:
x

       age  job  marital  education  balance  housing  duration  campaign
0     30.0   10        1          0     1787        0      79.0         1
1     33.0    7        1          1     4789        1     220.0         1
2     35.0    4        2          2     1350        1     185.0         1
3     30.0    4        1          2     1476        1     199.0         4
4     59.0    1        1          1        0        1     226.0         1
...    ...  ...      ...        ...      ...      ...       ...       ...
4496  99.0    7        1          1     -333        1     329.0         5
4497  57.0    6        1          2    -3313        1    -153.0         1
4498  57.0    9        1          1      295        0     151.0        11
4499  28.0    1        1          1     1137        0     129.0         4
4500  44.0    2        2          2     1136        1     345.0         2

[4501 rows x 8 columns]

In [118]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4496    0
4497    0
4498    0
4499    0
4500    0
Name: approval, Length: 4501, dtype: int64